### ISSUE TITLE
No css output if Brackets "Lint Files on Save" is off.

### ISSUE THREAD

**Issue by iamelru** [jdiehl/brackets-less-autocompile#95]
Hello!
So i have linting off by default, and that kills css output. 
`// out:` or compile.json does not help
Is "Lint Files on Save" checked really neccesary for your extension to work properly?

brackets 1.7, 
LESS AC 1.1.10

Oh, and console gives me that.
`Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:467:36)
    at n (file:///D:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:19:405)
    at Object.<anonymous> (file:///C:/Users/El/AppData/Roaming/Brackets/extensions/user/jdiehl.less-autocompile/main.js:123:3)
    at Object.context.execCb (file:///D:/Program%20Files%20(x86)`

**Comment by jdiehl** [comment]
I am hooking into the linter because it gives me a well-defined event when documents change and an easy way to report errors. I would recommend turning on linting and disabling the error console. This way the other linters shouldn't bother you too much. Be aware that less errors will be hidden as well
